# [build]
# publish = "dist"
# command = "pnpm run build"

[build.environment]
# This enables postinstall scripts which are needed for native dependencies like sharp
NPM_CONFIG_IGNORE_SCRIPTS = "false"
PNPM_IGNORE_SCRIPTS = "false"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
    public,
    max-age=0,
    must-revalidate
    '''
